# Generated by Django 4.0.6 on 2022-07-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='instagran',
            new_name='instagram',
        ),
    ]
