# Generated by Django 4.0.6 on 2022-07-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Features',
            new_name='Feature',
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature'},
        ),
    ]
